spring.application.name=fitzen_api
#server.address=172.22.22.139
server.port=8084
server.servlet.context-path=/fitzen
# Changes done by Siddharth for TSL 1.2 on 04/11/2025 Start

#server.ssl.enabled=true
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=changeit
#server.ssl.key-store-type=PKCS12
#server.ssl.enabled-protocols=TLSv1.2