name: Daily Java Q&A Automation

on:
  push:
    branches:
      - master
  schedule:
    #- cron: '0 3 * * *'   # Runs daily (UTC)
    - cron: '0 */4 * * *'  # runs every 4 hours
  workflow_dispatch:       # Manual trigger button

permissions:
  contents: write   # ✅ REQUIRED

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Script
        run: python automation/scripts/main.py